import 'package:serverpod/serverpod.dart';
import '../generated/protocol.dart';

class AuthEndpoint extends Endpoint {
  /// Create a new user session after login
  Future<UserSession> createSession(
    Session session,
    String userId,
    String deviceId,
    String? deviceName,
    String? deviceType,
  ) async {
    final now = DateTime.now();
    final userSession = UserSession(
      userId: userId,
      deviceId: deviceId,
      deviceName: deviceName,
      deviceType: deviceType,
      ipAddress: null,
      userAgent: null,
      accessToken: '', // Generated by auth module
      refreshToken: '', // Generated by auth module
      securityLevel: 'standard',
      isActive: true,
      expiresAt: now.add(const Duration(hours: 24)),
      lastActivityAt: now,
      createdAt: now,
    );
    return await UserSession.db.insertRow(session, userSession);
  }

  /// Revoke a session (logout)
  Future<bool> revokeSession(Session session, int sessionId) async {
    final existing = await UserSession.db.findById(session, sessionId);
    if (existing == null) return false;
    existing.isActive = false;
    await UserSession.db.updateRow(session, existing);
    return true;
  }

  /// Get active sessions for current user
  Future<List<UserSession>> getActiveSessions(Session session) async {
    final authInfo = session.authenticated;
    if (authInfo == null) return [];
    return await UserSession.db.find(
      session,
      where: (t) => t.userId.equals(authInfo.userIdentifier) & t.isActive.equals(true),
    );
  }

  /// Log a security event
  Future<SecurityEvent> logSecurityEvent(
    Session session,
    String? userId,
    String eventType,
    String severity,
    String? details,
  ) async {
    final event = SecurityEvent(
      userId: userId,
      eventType: eventType,
      severity: severity,
      ipAddress: null,
      details: details,
      createdAt: DateTime.now(),
    );
    return await SecurityEvent.db.insertRow(session, event);
  }

  /// Get security events for a user
  Future<List<SecurityEvent>> getSecurityEvents(
    Session session,
    String userId, {
    int limit = 50,
  }) async {
    return await SecurityEvent.db.find(
      session,
      where: (t) => t.userId.equals(userId),
      limit: limit,
      orderBy: (t) => t.createdAt,
      orderDescending: true,
    );
  }
}
