apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vertivo-dev
  namespace: argocd
spec:
  description: Vertivo IoT Platform - Development Environment
  sourceRepos:
    - '*'
  destinations:
    - namespace: vertivo-dev
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: PersistentVolumeClaim
    - group: apps
      kind: Deployment
    - group: apps.emqx.io
      kind: EMQX
