name: vertivo_widgetbook
description: "Catálogo de widgets de Vertivo con Widgetbook — taxonomía Atomic Design."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  widgetbook_annotation: ^3.10.0
  widgetbook: ^3.21.0
  vertivo_ui:
    path: ../../packages/vertivo_ui
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=3.0.0 <7.0.0'
  build_runner: ^2.4.0
  widgetbook_generator: ^3.21.0

flutter:
  uses-material-design: true
